### ISSUE TITLE
Feature: Mac Bindings

### ISSUE THREAD

**Issue by mackenly** [sp4ghet/ndi-rs#12]
What all would be involved in adding support for Mac OS? Is there a limitation or compatibility issue, or just a matter of adding the SDK files, running the code gen, and detecting the correct OS bindings to use?

I might try to take a pass at it and see.

**Comment by fivebats** [comment]
@mackenly : I found it was pretty easy to modify for Mac OS and NDI 5. But I referenced the files from the default NDK SDK installer rather than creating a `thirdparty/Mac` folder because  isn't clear to me that the NDI SDK terms permit distribution of anything except for `libndi.dylib`.   That's why I haven't submitted a pull request.

**Comment by mackenly** [comment]
That is a good point on SDK licensing. I'll probably stay away from publically open sourcing it with that in mind.
